### ISSUE TITLE
split BN plugin to a submodule?

### ISSUE THREAD

**Issue by psifertex** [fgsect/JMPscare#1]
Is it possible to split the BN plugin to a submodule? Currently subfolders aren't supported with the existing plugin manager and I'd be nice to have the plugin available for easy discovery in the plugin manager.

**Comment by pr0me** [comment]
Very good point, thanks, we will do so shortly!

**Comment by psifertex** [comment]
Awesome! That plus [creating a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) is all we need to add it to the plugin manager. 👍

**Comment by pr0me** [comment]
Done, you can find it at https://github.com/fgsect/JMPscare-binja :)

I've created an issue in the community-plugins repo. 
Please let us know if there's anything else for us to do and thanks for the heads-up again!
